---
- hosts: webserver
  become: true
  tasks:
   - name: Adicionar usuario helpdesk
     user: name=helpdesk state=present shell=/bin/bash password=$1$5b7Sfh3n$5c9Zibk.EYK4GrHHK3fz91
   
   - name: cria diretorio .ssh
     ansible.builtin.file:
       path: /home/ansible/.ssh
       state: directory
       owner: ansible
       group: ansible
   - name: copia chave ssh
     tags: copia_chave
     copy:
       src: /tmp/chave.key
       owner: ansible
       group: ansible
       dest: /home/ansible/.ssh
