---

- hosts: local
  become: true
  tasks:

  - name: instalar apache2
    apt:
      name: apache2
      state: absent

  - name: add php suppot for apache
    apt: 
      name: libapache2-mod-php
      state: absent
